// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGJcSE9EmhBmyXELX_Xuw9CoBCsEaOSEs',
    appId: '1:969691995103:web:7e075f42fd57766d6d426a',
    messagingSenderId: '969691995103',
    projectId: 'gcw-2026-9be48',
    authDomain: 'gcw-2026-9be48.firebaseapp.com',
    storageBucket: 'gcw-2026-9be48.firebasestorage.app',
    measurementId: 'G-6JJWXKDV4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT26jDR60xyVd7_mM83dE9uzL1mxWY6r0',
    appId: '1:969691995103:android:df0543df37c22ece6d426a',
    messagingSenderId: '969691995103',
    projectId: 'gcw-2026-9be48',
    storageBucket: 'gcw-2026-9be48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlGs4nwKWD1FcwzVULaw95I2E5DOjA5hY',
    appId: '1:969691995103:ios:c92874e57c5cfa996d426a',
    messagingSenderId: '969691995103',
    projectId: 'gcw-2026-9be48',
    storageBucket: 'gcw-2026-9be48.firebasestorage.app',
    iosBundleId: 'com.example.cgwHacktathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlGs4nwKWD1FcwzVULaw95I2E5DOjA5hY',
    appId: '1:969691995103:ios:c92874e57c5cfa996d426a',
    messagingSenderId: '969691995103',
    projectId: 'gcw-2026-9be48',
    storageBucket: 'gcw-2026-9be48.firebasestorage.app',
    iosBundleId: 'com.example.cgwHacktathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGJcSE9EmhBmyXELX_Xuw9CoBCsEaOSEs',
    appId: '1:969691995103:web:1031d41123b7dc356d426a',
    messagingSenderId: '969691995103',
    projectId: 'gcw-2026-9be48',
    authDomain: 'gcw-2026-9be48.firebaseapp.com',
    storageBucket: 'gcw-2026-9be48.firebasestorage.app',
    measurementId: 'G-RL9NJN1ZVC',
  );
}
